config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/profile.rb
class Profile < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :address,   class_name: 'Prefecture'
  belongs_to_active_hash :workplace, class_name: 'Prefecture'

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile

  validates :name, length: { maximum: 25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @user.build_profile if @user.profile == nil
  end
  
  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      flash[:alert] = '編集権限がありません'
      redirect_to root_path
    end

    @profile = @user.profile || @user.build_profile
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
- provide :page_title, 'Home'

h1 トップページ（テスト）

p テストページです。

app/views/layouts/_header.html.slim
nav.uk-navbar-container.uk-margin.uk-margin-remove-top uk-navbar=""
  .uk-navbar-center.uk-width-3xlarge
    .uk-margin-remove class="uk-width-1-3@s"
      .uk-flex.uk-flex-center
        ul.uk-navbar-nav
          li
            = link_to '', '#', class: 'uk-navbar-toggle uk-padding-remove', "uk-navbar-toggle-icon": ""
            .uk-navbar-dropdown
              ul.uk-nav.uk-navbar-dropdown-nav
                li
                  = link_to 'ピックアップ', '#'
                li
                  = link_to 'カテゴリー', '#'
        = link_to 'staXtock', root_path, class: 'uk-navbar-item uk-logo'
    .uk-margin-remove class="uk-width-1-3@s"
      .uk-flex.uk-flex-center
        .uk-navbar-item
            form.uk-search.uk-search-default
              = link_to '', '', 'uk-search-icon': ''
              input.uk-search-input placeholder="" type="search" /
    .uk-margin-remove class="uk-width-1-3@s"
      .uk-flex.uk-flex-around
        .uk-navbar-item.uk-width-medium.uk-flex.uk-flex-around
          - if signed_in?
            = link_to 'SignOut', destroy_user_session_path, method: :delete, class: 'uk-button uk-button-text'
            = link_to 'MyPage', user_path(current_user), class: 'uk-button uk-button-default'
          - else
            = link_to 'SignUp', new_user_registration_path, class: 'uk-button uk-button-text'
            = link_to 'SignIn', new_user_session_path, class: 'uk-button uk-button-default'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      => yield(:page_title)
      || StaxtockApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    - if flash[:notice]
      .uk-alert-success.uk-margin-remove uk-alert=""
        a.uk-alert-close uk-close="" 
        p = flash[:notice]
    - if flash[:alert]
      .uk-alert-danger.uk-margin-remove uk-alert=""
        a.uk-alert-close uk-close="" 
        p = flash[:alert]
    = render './layouts/header'
    = yield

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br

app/views/users/show.html.slim
.uk-container.uk-container-large
  .uk-grid.uk-grid-divider uk-grid="" 
    div class="uk-width-large@m"
      .uk-margin-large.uk-padding-large
        h3.uk-text-center ユーザー情報欄
        .uk-text-center
          | #{@user.name} @#{@user.id}
        .uk-text-center.uk-text-small
          | #{@user.email}, #{@user.profile.website || 'no data'}
        .uk-text-center.uk-margin-medium
          .uk-grid.uk-grid-divider uk-grid=""
            div class="uk-width-1-2@s"
              .uk-text-small スタック数
              .uk-text-medium 12/28d
            div class="uk-width-1-2@s"
              .uk-text-small スタック時間
              .uk-text-medium 50.5h/28d
            div class="uk-width-1-2@s"
              .uk-text-small フォロー数
              .uk-text-medium 134
            div class="uk-width-1-2@s"
              .uk-text-small フォロワー数
              .uk-text-medium 250
            
        p アバター、ユーザー名、アカウントID、投稿数、フォロー数、フォロワー数、プロフィール編集へのリンクを配置予定
        - if @user == current_user
          .uk-text-center
            = link_to 'プロフィールを編集する', edit_user_path(current_user), class: 'uk-button uk-button-primary'
    div class="uk-width-expand@m"
      .uk-margin-small-top
        ul.uk-flex-center uk-tab="" 
          li
            = link_to 'スタックレコード', '#'
          li
            = link_to 'ダイレクトメッセージ', '#'
          li
            = link_to 'フォロー', '#'
          li
            = link_to 'フォロワー', '#'
        ul.uk-switcher.uk-margin
          li
            p ここにスタックレコードが入ります
          li
            p ここにダイレクトメッセージ
          li
            p ここにフォロー
          li
            p ここにフォロワー